apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: magalixcorp/sample-api:v1
        imagePullPolicy: IfNotPresent
        name: frontend
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-password
              key: redis-password
          volumeMounts:
          - name: config-volume
            mountPath: /app/config.json
            subPath: config.json
          volumes:
          - name: config-volume
            configMap:
            name: app-config
